version: '3'

services:
  php:
    image: php:7.4-cli
    volumes:
    - ./:/app
    working_dir: /app

  composer:
    image: composer:latest
    volumes:
    - ./:/app
    working_dir: /app
    command: composer update
