name: CI

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cs:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: Coding standard
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Composer Update
        run: composer update

      - name: CS Check
        run: vendor/bin/phpcs --standard=ruleset.xml --extensions=php,phpt src/ tests/

  phpstan:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: PHPStan lv. 7
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Composer Update
        run: composer update

      - name: PHPStan lv. 7
        run: vendor/bin/phpstan.phar analyse -l 7 src

  unit:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      matrix:
        version: [ 7.4, 8.0, 8.1 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}

      - name: Composer Update
        run: composer update

      - name: Nette Tester
        run: vendor/bin/tester tests/
