name: CI
on:
  push:
    branches-ignore:
      - 'master'

jobs:
  runTasks:
    name: Run CI Tasks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Composer
        run: docker-compose run composer update --no-interaction --prefer-dist

      - name: Coding Standard
        run: docker-compose run php make cs

      - name: PHPStan lv.8
        run: docker-compose run php make phpstan

      - name: Tests Unit
        run: docker-compose run php make unit-tests
